### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by WWYong3** [alanzty/KCR-Official#3]
Hello, I would like to ask why the loss of the target domain in the second stage RCNN does not include the loss of bounding box regression. Is there any reason for this?

**Comment by alanzty** [comment]
Hi,
This is omitted as the potential benefit is minimal compared to the increased complexity. The upper bound gain of having a projection regression loss is  full-supervision with ground truth (gt) rotation. With a fixed KCR-RPN, we conduct an ablation that introduces gt rotation to the RCNN stage. We compare 1) No gt rotation, 2) gt rotation to assignment process only, and 3) gt rotation to both assignment and regression. Our results in Table shows that the significance of the fully-supervised regression (upper bound) is small. Adding a RCNN projection loss will dramatically increase the complexity because the loss is residual based in delta form. 

I appreciate that you have paid the detailed attention to our paper. 
![Screenshot 2023-08-27 145043](https://github.com/alanzty/KCR-Official/assets/33640705/a4317a42-2c14-4db5-819a-1f3bcfe2ad4f)
